### ISSUE TITLE
🎓 Develop CA v2 Workshop

### ISSUE THREAD

**Issue by william-liebenberg** [SSWConsulting/SSW.CleanArchitecture#32]
```[tasklist]
- [x] Part 1 - Bad example demo for the Workshop
- [x] Part 1 - CA version of Spaghetti Commerce @matt-goldman
- [x] Part 1 - Demo Steps from Spaghetti to Lasagna @matt-goldman
- [x] Let Camilla know by early June 5 if CA workshop will be ready for July
- [x] Update 1-day marketing content on SSW website
- [x] Update 2-day marketing content on SSW website
- [x] Part 2 - Cafe 365
- [ ] Part 3 - Testing
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/129
- [ ] ✨ Publish rules for new CA features
```

**Comment by matt-goldman** [comment]
@william-liebenberg comments on the high-level changes:

# Structural

* Rather than build the CA solution from scratch, we will use the template.
* Building the solution from scratch is cool, but it doesn't show the pain (and by extension the benefit).
* Instead, we'll add features and explain how to use CA in practice.
* This affords us the opportunity to focus on the principles of CA as well as the practical application of it, rather than how to build it.

# Added

* Bad example (SpaghettiCommerce: https://github.com/SSWConsulting/SpaghettiCommerce)
    - makes it relatable for attendees
    - shows the pain
* More theory
    - principles of CA
    - how what we're doing relates to CA
* Add a feature
    - attendees leave knowing _how_ to use the template in their own solutions
* Ardalis specification
* Unit tests
 
# Removed

In general, things that QoL improvements (rather than architectural concerns) will be addressed, but we won't go through them in detail. For example:

* Progression from projections to Automapper
* FluentValidation
* JWT support in Swagger
* Logging Behaviour
* Health checks

Other things removed entirely:

* AuditableEntity
* Guard clauses
* Integration with ASP.NET Core Identity

**Comment by danielmackay** [comment]
Mostly Done - first workshop will be delivered tomorrow.  Rules can be added as needed afterwards.
